apiVersion: v1
kind: Service
metadata:
  name: kine-with-mysql-service
  namespace: wardle
  labels:
    app: kine
spec:
  type: ClusterIP
  selector:
   app: kine
  ports:
   - name: https
     protocol: TCP
     port: 23790
     targetPort: 2379